### ISSUE TITLE
Spawn Horse Egg not working

### ISSUE THREAD

**Issue by MrAmericanMike** [MinecraftModDevelopment/p455w0rdsThings#10]
Whenever I try to spawn a horse in the world, I'm getting a pig when p455w0rdsThings is installed.

Using version:
p455w0rdsthings-1.10.2-0.2.3a

**Comment by p455w0rd** [comment]
Yup..I found this one a while back, It's due to the horse armor code in the current public version. I have fixed this issue in the coming update. Thanks :)
