### ISSUE TITLE
Personal Pack Crash Issue

### ISSUE THREAD

**Issue by RJKoubaka** [MinecraftModDevelopment/p455w0rdsThings#11]
There appears to be an issue causing my personally created pack to crash when using p455w0rd's and Bookshelf. Here is a link to my reddit post, which contains the crash log. I can run the pack without issue by removing p455w0rd's. 

https://www.reddit.com/r/FeedTheBeastCrashes/comments/5812gn/personal_pack_crashing_idd_the_mod/

**Comment by p455w0rd** [comment]
yeah it's cuz of bookshelf updating..thx Darkhax :P He refactored stuff in Bookshelf without giving me the heads up..i've been working on a pretty big update for over a week now..it should be going up tomorrow..Bookshelf is will no longer be a dependency
