### ISSUE TITLE
Armor not giving listed protection value

### ISSUE THREAD

**Issue by togreglove** [MinecraftModDevelopment/p455w0rdsThings#15]
I'm finding that the armor value on the upgraded carbon armor does not match the listed stats.  For example, my Emerald Infused Carbon Chestplate with Jetpack lists armor at +11, but I only get one shirt of protection.  I believe a full set gives 4 or 4.5 shirts.  I tested to see if it still protects as if it was +11, and it does not.

**Comment by p455w0rd** [comment]
Does the armor have a charge? I will look into this in the mean time.

**Comment by p455w0rd** [comment]
okay, so thankfully this was just a visual glitch..the armor actually functions as it should..I'll do my best to get an update out tongiht, thanks for the report

**Comment by togreglove** [comment]
Odd, it doesn't seem to protect like it has the higher protection value. I'll test some more after the update

**Comment by p455w0rd** [comment]
Could have been..I did change a bit of the logic, but it seems to work for me as of the latest update which is available on CurseForge.
