### ISSUE TITLE
Chunkloader Duplicate Id Crash

### ISSUE THREAD

**Issue by WenXin20** [MinecraftModDevelopment/p455w0rdsThings#16]
Forge 1.10.2-2107
p455w0rds: v1.0.0
It crashes on game launch.
[Crash Log](http://pastebin.com/hEBGpW4m)

**Comment by p455w0rd** [comment]
Are you sure you removed the old PWThings jar from your mods folder? I am unable to reproduce this. Tested in deobfuscated integrated server, deobfuscated dedicated server, obfuscated integrated server, and obfuscated dedicated server. Loads fine in all scenarios.

**Comment by WenXin20** [comment]
I'm pretty sure I did, that was the first time trying the mod. Maybe it's somehow conflictin with another mod?

**Comment by knoxhack** [comment]
I had the same problem. I think its caused because NEOTech's chunkloader or IC2's has the same registry name as this

**Comment by p455w0rd** [comment]
well I have changed the ID in my local version since, so I'll download every mod I can find that has a chunkloader and see if I can replicate. Should be good in next update. Thanks knox
