### ISSUE TITLE
/dank/null UI crashes with an IndexOutOfBoundsException

### ISSUE THREAD

**Issue by swyrl** [MinecraftModDevelopment/p455w0rdsThings#17]
Running forge v 12.18.2.2112, Java 8 64bit.
Opening the UI crashes the game.
 [crash-2016-10-26_22.17.58-client.txt](https://github.com/MinecraftModDevelopment/p455w0rdsThings/files/556111/crash-2016-10-26_22.17.58-client.txt)

**Comment by p455w0rd** [comment]
Can you please provide me with a mod list, and if you could, test using only p455w0rd's Things, CodeChickenLib, and Tesla to see if you get the same result. I am having no issues, this can only be the result of mod interaction. It could be on my end or the other mod's, but p455w0rd's Things functions fine by itself, thanks.

**Comment by p455w0rd** [comment]
Since it has been over 24 hours and you have failed to reply, I'm going to close this issue.

**Comment by swyrl** [comment]
Apologies for the delay, I've been busy. tested with a clean install, and it works just fine. Going to dig around and see if I can figure out what's conflicting
