### ISSUE TITLE
Crash when Cyclic is installed.

### ISSUE THREAD

**Issue by swyrl** [MinecraftModDevelopment/p455w0rdsThings#19]
Opening the /dank/null gui will crash the game if cyclic is installed. (Tested with and without other mods installed. This crash log is from a clean install with just Cyclic, p455w0rdsThings, and dependencies.)
[crash-2016-10-31_21.06.10-client.txt](https://github.com/MinecraftModDevelopment/p455w0rdsThings/files/563153/crash-2016-10-31_21.06.10-client.txt)

Tested on latest forge & Java, 64-bit.

**Comment by swyrl** [comment]
UPDATE: Disabling the quick move buttons in Cyclic fixes the problem. Apparently the /dank/null UI just doesn't like rendering buttons or something.

**Comment by p455w0rd** [comment]
I really don't see how my mod would have anything to do with that. If that mod for some reason renders buttons on to every GuiContainer, it's just poor coding. It should not render on any other mod's GuiContainer by default. Instead it should have an API where other mods can opt-in to use the functionality. A good example of this is Inventory Tweaks. Nonetheless, I'll skim my code and see if I can find anything. Thanks for the report.

**Comment by swyrl** [comment]
PrinceofAmber Is already disabling it on his end, but thanks for looking into it :).
