### ISSUE TITLE
Flux modifier

### ISSUE THREAD

**Issue by Phocks7** [MinecraftModDevelopment/p455w0rdsThings#21]
Do you think you could add a modifier for tinkers' tools to accept RF/telsa, and loose charge instead of taking damage (1.7.10 style)? You could use the batteries from your mod for the recipe. Presumably you'd need enderio to charge the tools, though.

**Comment by p455w0rd** [comment]
all my stuff supports Tesla and RF...it just doesn the conversion internally..I'll look into this

**Comment by Phocks7** [comment]
Yeah, I was just wondering how you'd charge them, since there's no Energetic Infuser in 1.10.

**Comment by p455w0rd** [comment]
I'll be adding machines back soon..PWThing had machines at one point..they got removed..i learned stuff since then, so I'll be re-adding them
