### ISSUE TITLE
SMP Player Right-Click error? Doesn't Crash.

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftModDevelopment/p455w0rdsThings#8]
https://gist.github.com/Shadows-of-Fire/aa2f1ea6053cf165f0255ad038cf82e6
Right clicking another player causes that to happen about 4 times in the console.  Doesn't actually do anything.

**Comment by p455w0rd** [comment]
already been fixed :) new update will have a lot of bugfixes
